#!/bin/bash


aws cloudwatch put-metric-data --metric-name Connections --namespace MySQL --value $(mysql -Ne "show status like 'Threads_connected'"  | awk '{print$2}') --dimensions Server=$HOST_NAME
aws cloudwatch put-metric-data --metric-name MySQL --namespace Processes --value $(ps aux | grep -c mysq[l]) --dimensions Server=$HOST_NAME
