#!/bin/bash


aws cloudwatch put-metric-data --metric-name Connections --namespace Nginx --value $(curl -s localhost/nginx_status | grep Active | awk '{print$3}') --dimensions Server=$HOST_NAME
aws cloudwatch put-metric-data --metric-name Nginx --namespace Processes --value $(ps aux | grep -c ngin[x]:) --dimensions Server=$HOST_NAME

