#!/bin/bash


aws cloudwatch put-metric-data --metric-name Connections --namespace PHP-FPM --dimensions InstanceId=$INSTANCE --value $(ps aux | grep -c php-fp[m])
aws cloudwatch put-metric-data --metric-name PHP-FPM --namespace Processes --dimensions InstanceId=$INSTANCE --value $(ps aux | grep -c php-fp[m])
