#!/bin/bash

df -Ph | egrep "^/dev/" | grep -v "/san" | while read line
do
	/opt/aws-scripts-mon/mon-put-instance-data.pl --mem-util --disk-space-util --disk-path=$(echo $line | awk '{print$6}')
done
aws cloudwatch put-metric-data --metric-name Load --namespace System/Linux --value $(cat /proc/loadavg  | awk '{print$1}') --dimensions Server=$HOST_NAME
aws cloudwatch put-metric-data --metric-name IOWait --namespace System/Linux --value $(iostat 1 2 | grep -A1 avg-cpu | tail -1 | awk '{print$4}') --unit Percent --dimensions Server=$HOST_NAME

memtotal=$(awk '/MemTotal/ {print$2}' /proc/meminfo)
memfree=$(awk '/MemAvailable/ {print$2}' /proc/meminfo)
let "memused=100-memfree*100/memtotal"
aws cloudwatch put-metric-data --metric-name UsedMemoryPercent --namespace System/Linux --value $memused --dimensions Server=$HOST_NAME
